
package sk.stuba.fiit.labss2.pis.validator;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ValidatorService", targetNamespace = "http://labss2.fiit.stuba.sk/pis/validator", wsdlLocation = "http://labss2.fiit.stuba.sk/pis/ws/Validator?WSDL")
public class ValidatorService
    extends Service
{

    private final static URL VALIDATORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sk.stuba.fiit.labss2.pis.validator.ValidatorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sk.stuba.fiit.labss2.pis.validator.ValidatorService.class.getResource(".");
            url = new URL(baseUrl, "http://labss2.fiit.stuba.sk/pis/ws/Validator?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://labss2.fiit.stuba.sk/pis/ws/Validator?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VALIDATORSERVICE_WSDL_LOCATION = url;
    }

    public ValidatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidatorService() {
        super(VALIDATORSERVICE_WSDL_LOCATION, new QName("http://labss2.fiit.stuba.sk/pis/validator", "ValidatorService"));
    }

    /**
     * 
     * @return
     *     returns ValidatorPortType
     */
    @WebEndpoint(name = "ValidatorPort")
    public ValidatorPortType getValidatorPort() {
        return super.getPort(new QName("http://labss2.fiit.stuba.sk/pis/validator", "ValidatorPort"), ValidatorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidatorPortType
     */
    @WebEndpoint(name = "ValidatorPort")
    public ValidatorPortType getValidatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://labss2.fiit.stuba.sk/pis/validator", "ValidatorPort"), ValidatorPortType.class, features);
    }

}
