
package sk.stuba.fiit.labss2.pis.validator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import sk.stuba.fiit.labss2.pis.validator.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ValidatorPortType", targetNamespace = "http://labss2.fiit.stuba.sk/pis/validator")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidatorPortType {


    /**
     * 
     * @param email
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/validator/#validateEmail")
    @WebResult(name = "success", targetNamespace = "")
    @RequestWrapper(localName = "validateEmail", targetNamespace = "http://labss2.fiit.stuba.sk/pis/validator/types", className = "sk.stuba.fiit.labss2.pis.validator.types.ValidateEmail")
    @ResponseWrapper(localName = "validateEmailResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/validator/types", className = "sk.stuba.fiit.labss2.pis.validator.types.ValidateEmailResponse")
    public boolean validateEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param phone
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/validator/#validatePhone")
    @WebResult(name = "success", targetNamespace = "")
    @RequestWrapper(localName = "validatePhone", targetNamespace = "http://labss2.fiit.stuba.sk/pis/validator/types", className = "sk.stuba.fiit.labss2.pis.validator.types.ValidatePhone")
    @ResponseWrapper(localName = "validatePhoneResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/validator/types", className = "sk.stuba.fiit.labss2.pis.validator.types.ValidatePhoneResponse")
    public boolean validatePhone(
        @WebParam(name = "phone", targetNamespace = "")
        String phone);

}
