
package sk.stuba.fiit.labss2.pis.students.team076zlava;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import sk.stuba.fiit.labss2.pis.students.team076zlava.types.ArrayOfIds;
import sk.stuba.fiit.labss2.pis.students.team076zlava.types.ArrayOfZlavas;
import sk.stuba.fiit.labss2.pis.students.team076zlava.types.ObjectFactory;
import sk.stuba.fiit.labss2.pis.students.team076zlava.types.Zlava;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Team076ZlavaPortType", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Team076ZlavaPortType {


    /**
     * 
     * @param id
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076zlava.types.Zlava
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/#getById")
    @WebResult(name = "zlava", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.GetByIdResponse")
    public Zlava getById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param attributeValue
     * @param ids
     * @param attributeName
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076zlava.types.ArrayOfZlavas
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/#getByAttributeValue")
    @WebResult(name = "zlavas", targetNamespace = "")
    @RequestWrapper(localName = "getByAttributeValue", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.GetByAttributeValue")
    @ResponseWrapper(localName = "getByAttributeValueResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.GetByAttributeValueResponse")
    public ArrayOfZlavas getByAttributeValue(
        @WebParam(name = "attribute_name", targetNamespace = "")
        String attributeName,
        @WebParam(name = "attribute_value", targetNamespace = "")
        String attributeValue,
        @WebParam(name = "ids", targetNamespace = "")
        ArrayOfIds ids);

    /**
     * 
     * @param attributeValue
     * @param mathCondition
     * @param ids
     * @param attributeName
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076zlava.types.ArrayOfZlavas
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/#getByNumericCondition")
    @WebResult(name = "zlavas", targetNamespace = "")
    @RequestWrapper(localName = "getByNumericCondition", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.GetByNumericCondition")
    @ResponseWrapper(localName = "getByNumericConditionResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.GetByNumericConditionResponse")
    public ArrayOfZlavas getByNumericCondition(
        @WebParam(name = "attribute_name", targetNamespace = "")
        String attributeName,
        @WebParam(name = "attribute_value", targetNamespace = "")
        String attributeValue,
        @WebParam(name = "math_condition", targetNamespace = "")
        String mathCondition,
        @WebParam(name = "ids", targetNamespace = "")
        ArrayOfIds ids);

    /**
     * 
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076zlava.types.ArrayOfZlavas
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/#getAll")
    @WebResult(name = "zlavas", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.GetAllResponse")
    public ArrayOfZlavas getAll();

    /**
     * 
     * @param zlava
     * @param teamId
     * @param teamPassword
     * @return
     *     returns int
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/#insert")
    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.InsertResponse")
    public int insert(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "Zlava", targetNamespace = "")
        Zlava zlava);

    /**
     * 
     * @param zlava
     * @param teamId
     * @param entityId
     * @param teamPassword
     * @return
     *     returns int
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/#update")
    @WebResult(name = "updates", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.UpdateResponse")
    public int update(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "entity_id", targetNamespace = "")
        int entityId,
        @WebParam(name = "Zlava", targetNamespace = "")
        Zlava zlava);

    /**
     * 
     * @param teamId
     * @param entityId
     * @param teamPassword
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/#delete")
    @WebResult(name = "deleted", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zlava/types", className = "sk.stuba.fiit.labss2.pis.students.team076zlava.types.DeleteResponse")
    public boolean delete(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "entity_id", targetNamespace = "")
        int entityId);

}
