
package sk.stuba.fiit.labss2.pis.students.team076majitel;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Team076MajitelService", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076majitel", wsdlLocation = "http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Majitel?WSDL")
public class Team076MajitelService
    extends Service
{

    private final static URL TEAM076MAJITELSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sk.stuba.fiit.labss2.pis.students.team076majitel.Team076MajitelService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sk.stuba.fiit.labss2.pis.students.team076majitel.Team076MajitelService.class.getResource(".");
            url = new URL(baseUrl, "http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Majitel?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Majitel?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEAM076MAJITELSERVICE_WSDL_LOCATION = url;
    }

    public Team076MajitelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Team076MajitelService() {
        super(TEAM076MAJITELSERVICE_WSDL_LOCATION, new QName("http://labss2.fiit.stuba.sk/pis/students/team076majitel", "Team076MajitelService"));
    }

    /**
     * 
     * @return
     *     returns Team076MajitelPortType
     */
    @WebEndpoint(name = "Team076MajitelPort")
    public Team076MajitelPortType getTeam076MajitelPort() {
        return super.getPort(new QName("http://labss2.fiit.stuba.sk/pis/students/team076majitel", "Team076MajitelPort"), Team076MajitelPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Team076MajitelPortType
     */
    @WebEndpoint(name = "Team076MajitelPort")
    public Team076MajitelPortType getTeam076MajitelPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://labss2.fiit.stuba.sk/pis/students/team076majitel", "Team076MajitelPort"), Team076MajitelPortType.class, features);
    }

}
