
package sk.stuba.fiit.labss2.pis.students.team076zakaznik;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Team076ZakaznikService", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik", wsdlLocation = "http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Zakaznik?WSDL")
public class Team076ZakaznikService
    extends Service
{

    private final static URL TEAM076ZAKAZNIKSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sk.stuba.fiit.labss2.pis.students.team076zakaznik.Team076ZakaznikService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sk.stuba.fiit.labss2.pis.students.team076zakaznik.Team076ZakaznikService.class.getResource(".");
            url = new URL(baseUrl, "http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Zakaznik?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Zakaznik?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEAM076ZAKAZNIKSERVICE_WSDL_LOCATION = url;
    }

    public Team076ZakaznikService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Team076ZakaznikService() {
        super(TEAM076ZAKAZNIKSERVICE_WSDL_LOCATION, new QName("http://labss2.fiit.stuba.sk/pis/students/team076zakaznik", "Team076ZakaznikService"));
    }

    /**
     * 
     * @return
     *     returns Team076ZakaznikPortType
     */
    @WebEndpoint(name = "Team076ZakaznikPort")
    public Team076ZakaznikPortType getTeam076ZakaznikPort() {
        return super.getPort(new QName("http://labss2.fiit.stuba.sk/pis/students/team076zakaznik", "Team076ZakaznikPort"), Team076ZakaznikPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Team076ZakaznikPortType
     */
    @WebEndpoint(name = "Team076ZakaznikPort")
    public Team076ZakaznikPortType getTeam076ZakaznikPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://labss2.fiit.stuba.sk/pis/students/team076zakaznik", "Team076ZakaznikPort"), Team076ZakaznikPortType.class, features);
    }

}
