
package sk.stuba.fiit.labss2.pis.students.team076zakaznik;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.ArrayOfIds;
import sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.ArrayOfZakazniks;
import sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.ObjectFactory;
import sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.Zakaznik;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Team076ZakaznikPortType", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Team076ZakaznikPortType {


    /**
     * 
     * @param id
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.Zakaznik
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/#getById")
    @WebResult(name = "zakaznik", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.GetByIdResponse")
    public Zakaznik getById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param attributeValue
     * @param ids
     * @param attributeName
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.ArrayOfZakazniks
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/#getByAttributeValue")
    @WebResult(name = "zakazniks", targetNamespace = "")
    @RequestWrapper(localName = "getByAttributeValue", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.GetByAttributeValue")
    @ResponseWrapper(localName = "getByAttributeValueResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.GetByAttributeValueResponse")
    public ArrayOfZakazniks getByAttributeValue(
        @WebParam(name = "attribute_name", targetNamespace = "")
        String attributeName,
        @WebParam(name = "attribute_value", targetNamespace = "")
        String attributeValue,
        @WebParam(name = "ids", targetNamespace = "")
        ArrayOfIds ids);

    /**
     * 
     * @param attributeValue
     * @param mathCondition
     * @param ids
     * @param attributeName
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.ArrayOfZakazniks
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/#getByNumericCondition")
    @WebResult(name = "zakazniks", targetNamespace = "")
    @RequestWrapper(localName = "getByNumericCondition", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.GetByNumericCondition")
    @ResponseWrapper(localName = "getByNumericConditionResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.GetByNumericConditionResponse")
    public ArrayOfZakazniks getByNumericCondition(
        @WebParam(name = "attribute_name", targetNamespace = "")
        String attributeName,
        @WebParam(name = "attribute_value", targetNamespace = "")
        String attributeValue,
        @WebParam(name = "math_condition", targetNamespace = "")
        String mathCondition,
        @WebParam(name = "ids", targetNamespace = "")
        ArrayOfIds ids);

    /**
     * 
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.ArrayOfZakazniks
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/#getAll")
    @WebResult(name = "zakazniks", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.GetAllResponse")
    public ArrayOfZakazniks getAll();

    /**
     * 
     * @param zakaznik
     * @param teamId
     * @param teamPassword
     * @return
     *     returns int
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/#insert")
    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.InsertResponse")
    public int insert(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "Zakaznik", targetNamespace = "")
        Zakaznik zakaznik);

    /**
     * 
     * @param zakaznik
     * @param teamId
     * @param entityId
     * @param teamPassword
     * @return
     *     returns int
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/#update")
    @WebResult(name = "updates", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.UpdateResponse")
    public int update(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "entity_id", targetNamespace = "")
        int entityId,
        @WebParam(name = "Zakaznik", targetNamespace = "")
        Zakaznik zakaznik);

    /**
     * 
     * @param teamId
     * @param entityId
     * @param teamPassword
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/#delete")
    @WebResult(name = "deleted", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076zakaznik/types", className = "sk.stuba.fiit.labss2.pis.students.team076zakaznik.types.DeleteResponse")
    public boolean delete(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "entity_id", targetNamespace = "")
        int entityId);

}
