
package sk.stuba.fiit.labss2.pis.students.team076kaviaren;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Team076KaviarenService", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076kaviaren", wsdlLocation = "http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Kaviaren?WSDL")
public class Team076KaviarenService
    extends Service
{

    private final static URL TEAM076KAVIARENSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sk.stuba.fiit.labss2.pis.students.team076kaviaren.Team076KaviarenService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sk.stuba.fiit.labss2.pis.students.team076kaviaren.Team076KaviarenService.class.getResource(".");
            url = new URL(baseUrl, "http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Kaviaren?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://labss2.fiit.stuba.sk/pis/ws/Students/Team076Kaviaren?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEAM076KAVIARENSERVICE_WSDL_LOCATION = url;
    }

    public Team076KaviarenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Team076KaviarenService() {
        super(TEAM076KAVIARENSERVICE_WSDL_LOCATION, new QName("http://labss2.fiit.stuba.sk/pis/students/team076kaviaren", "Team076KaviarenService"));
    }

    /**
     * 
     * @return
     *     returns Team076KaviarenPortType
     */
    @WebEndpoint(name = "Team076KaviarenPort")
    public Team076KaviarenPortType getTeam076KaviarenPort() {
        return super.getPort(new QName("http://labss2.fiit.stuba.sk/pis/students/team076kaviaren", "Team076KaviarenPort"), Team076KaviarenPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Team076KaviarenPortType
     */
    @WebEndpoint(name = "Team076KaviarenPort")
    public Team076KaviarenPortType getTeam076KaviarenPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://labss2.fiit.stuba.sk/pis/students/team076kaviaren", "Team076KaviarenPort"), Team076KaviarenPortType.class, features);
    }

}
