
package sk.stuba.fiit.labss2.pis.students.team076navsteva;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import sk.stuba.fiit.labss2.pis.students.team076navsteva.types.ArrayOfIds;
import sk.stuba.fiit.labss2.pis.students.team076navsteva.types.ArrayOfNavstevas;
import sk.stuba.fiit.labss2.pis.students.team076navsteva.types.Navsteva;
import sk.stuba.fiit.labss2.pis.students.team076navsteva.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Team076NavstevaPortType", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Team076NavstevaPortType {


    /**
     * 
     * @param id
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076navsteva.types.Navsteva
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/#getById")
    @WebResult(name = "navsteva", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.GetByIdResponse")
    public Navsteva getById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param attributeValue
     * @param ids
     * @param attributeName
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076navsteva.types.ArrayOfNavstevas
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/#getByAttributeValue")
    @WebResult(name = "navstevas", targetNamespace = "")
    @RequestWrapper(localName = "getByAttributeValue", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.GetByAttributeValue")
    @ResponseWrapper(localName = "getByAttributeValueResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.GetByAttributeValueResponse")
    public ArrayOfNavstevas getByAttributeValue(
        @WebParam(name = "attribute_name", targetNamespace = "")
        String attributeName,
        @WebParam(name = "attribute_value", targetNamespace = "")
        String attributeValue,
        @WebParam(name = "ids", targetNamespace = "")
        ArrayOfIds ids);

    /**
     * 
     * @param attributeValue
     * @param mathCondition
     * @param ids
     * @param attributeName
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076navsteva.types.ArrayOfNavstevas
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/#getByNumericCondition")
    @WebResult(name = "navstevas", targetNamespace = "")
    @RequestWrapper(localName = "getByNumericCondition", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.GetByNumericCondition")
    @ResponseWrapper(localName = "getByNumericConditionResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.GetByNumericConditionResponse")
    public ArrayOfNavstevas getByNumericCondition(
        @WebParam(name = "attribute_name", targetNamespace = "")
        String attributeName,
        @WebParam(name = "attribute_value", targetNamespace = "")
        String attributeValue,
        @WebParam(name = "math_condition", targetNamespace = "")
        String mathCondition,
        @WebParam(name = "ids", targetNamespace = "")
        ArrayOfIds ids);

    /**
     * 
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076navsteva.types.ArrayOfNavstevas
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/#getAll")
    @WebResult(name = "navstevas", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.GetAllResponse")
    public ArrayOfNavstevas getAll();

    /**
     * 
     * @param teamId
     * @param navsteva
     * @param teamPassword
     * @return
     *     returns int
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/#insert")
    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.InsertResponse")
    public int insert(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "Navsteva", targetNamespace = "")
        Navsteva navsteva);

    /**
     * 
     * @param teamId
     * @param navsteva
     * @param entityId
     * @param teamPassword
     * @return
     *     returns int
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/#update")
    @WebResult(name = "updates", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.UpdateResponse")
    public int update(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "entity_id", targetNamespace = "")
        int entityId,
        @WebParam(name = "Navsteva", targetNamespace = "")
        Navsteva navsteva);

    /**
     * 
     * @param teamId
     * @param entityId
     * @param teamPassword
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/#delete")
    @WebResult(name = "deleted", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076navsteva/types", className = "sk.stuba.fiit.labss2.pis.students.team076navsteva.types.DeleteResponse")
    public boolean delete(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "entity_id", targetNamespace = "")
        int entityId);

}
