
package sk.stuba.fiit.labss2.pis.students.team076hodnotenie;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.ArrayOfHodnotenies;
import sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.ArrayOfIds;
import sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.Hodnotenie;
import sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Team076HodnoteniePortType", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Team076HodnoteniePortType {


    /**
     * 
     * @param id
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.Hodnotenie
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/#getById")
    @WebResult(name = "hodnotenie", targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.GetByIdResponse")
    public Hodnotenie getById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param attributeValue
     * @param ids
     * @param attributeName
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.ArrayOfHodnotenies
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/#getByAttributeValue")
    @WebResult(name = "hodnotenies", targetNamespace = "")
    @RequestWrapper(localName = "getByAttributeValue", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.GetByAttributeValue")
    @ResponseWrapper(localName = "getByAttributeValueResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.GetByAttributeValueResponse")
    public ArrayOfHodnotenies getByAttributeValue(
        @WebParam(name = "attribute_name", targetNamespace = "")
        String attributeName,
        @WebParam(name = "attribute_value", targetNamespace = "")
        String attributeValue,
        @WebParam(name = "ids", targetNamespace = "")
        ArrayOfIds ids);

    /**
     * 
     * @param attributeValue
     * @param mathCondition
     * @param ids
     * @param attributeName
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.ArrayOfHodnotenies
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/#getByNumericCondition")
    @WebResult(name = "hodnotenies", targetNamespace = "")
    @RequestWrapper(localName = "getByNumericCondition", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.GetByNumericCondition")
    @ResponseWrapper(localName = "getByNumericConditionResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.GetByNumericConditionResponse")
    public ArrayOfHodnotenies getByNumericCondition(
        @WebParam(name = "attribute_name", targetNamespace = "")
        String attributeName,
        @WebParam(name = "attribute_value", targetNamespace = "")
        String attributeValue,
        @WebParam(name = "math_condition", targetNamespace = "")
        String mathCondition,
        @WebParam(name = "ids", targetNamespace = "")
        ArrayOfIds ids);

    /**
     * 
     * @return
     *     returns sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.ArrayOfHodnotenies
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/#getAll")
    @WebResult(name = "hodnotenies", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.GetAllResponse")
    public ArrayOfHodnotenies getAll();

    /**
     * 
     * @param teamId
     * @param hodnotenie
     * @param teamPassword
     * @return
     *     returns int
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/#insert")
    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.InsertResponse")
    public int insert(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "Hodnotenie", targetNamespace = "")
        Hodnotenie hodnotenie);

    /**
     * 
     * @param teamId
     * @param entityId
     * @param hodnotenie
     * @param teamPassword
     * @return
     *     returns int
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/#update")
    @WebResult(name = "updates", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.UpdateResponse")
    public int update(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "entity_id", targetNamespace = "")
        int entityId,
        @WebParam(name = "Hodnotenie", targetNamespace = "")
        Hodnotenie hodnotenie);

    /**
     * 
     * @param teamId
     * @param entityId
     * @param teamPassword
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/#delete")
    @WebResult(name = "deleted", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://labss2.fiit.stuba.sk/pis/students/team076hodnotenie/types", className = "sk.stuba.fiit.labss2.pis.students.team076hodnotenie.types.DeleteResponse")
    public boolean delete(
        @WebParam(name = "team_id", targetNamespace = "")
        String teamId,
        @WebParam(name = "team_password", targetNamespace = "")
        String teamPassword,
        @WebParam(name = "entity_id", targetNamespace = "")
        int entityId);

}
